### ISSUE TITLE
Commands in daily rewards not working

### ISSUE THREAD

**Issue by izeerF** [OakLoaf/LushRewards#21]
### When im trying to use any command (plugin and vanilla) while im trying to use ``/lushrewards:rewards`` its giving me this error:
```[14:45:43 ERROR]: Command exception: /lushrewards:rewards
org.bukkit.command.CommandException: Unhandled exception executing command 'lushrewards:rewards' in plugin LushRewards v3.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2200) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2174) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.lushplugins.lushrewards.gui.GuiFormat.getTemplate()" because the return value of "org.lushplugins.lushrewards.module.dailyrewards.DailyRewardsModule.getGuiFormat()" is null
        at LushRewards-3.2.0.jar/org.lushplugins.lushrewards.module.dailyrewards.DailyRewardsGui.<init>(DailyRewardsGui.java:32) ~[LushRewards-3.2.0.jar:?]
        at LushRewards-3.2.0.jar/org.lushplugins.lushrewards.command.RewardsCommand.lambda$execute$1(RewardsCommand.java:47) ~[LushRewards-3.2.0.jar:?]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at LushRewards-3.2.0.jar/org.lushplugins.lushrewards.command.RewardsCommand.execute(RewardsCommand.java:46) ~[LushRewards-3.2.0.jar:?]
        at LushRewards-3.2.0.jar/org.lushplugins.lushrewards.libraries.lushlib.command.Command.onCommand(Command.java:56) ~[LushRewards-3.2.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more```

**Comment by OakLoaf** [comment]
Hi there, could you send me the daily-rewards module file related to this error?

**Comment by izeerF** [comment]
Yeah, but its the default one but i just changed the rewards:
```daily-rewards:
  default:
    category: small
    display-item:
      lore:
        - "&#bdbebfNagrody: &o(jedna z)"
        - "&#bdbebf- 9 Żelaznych Sztabek"
        - "&#bdbebf- 1 Klucz do podstawowej skrzynki"
        - "&#bdbebf- 1 axolotl w wiaderku"
        - "&#bdbebf- 1 Klucz do epickiej skrzynki"
        - "&#bdbebf- 1 Ciasto"
        - "&#bdbebf- 3 Enderperły"
        - "&#bdbebf- 1 Węgiel drzewny :c"
    redeem-sound: ENTITY_EXPERIENCE_ORB_PICKUP
    rewards:
      - type: random
        rewards:
          - type: item
            material: iron_ingot
            amount: 9
          - type: command
	    commands:
	    - "crates key give %player% podstawowy_klucz 1"
          - type: item
            material: axolotl_bucket
            amount: 1
          - type: command
	    commands:
	    - "crates key give %player% epicki_klucz 1"
          - type: item
            material: diamond
            amount: 2
          - type: item
            material: cake
            amount: 1
          - type: item
            material: ender_pearl
            amount: 2
          - type: item
            material: charcoal
            amount: 1
```

**Comment by OakLoaf** [comment]
Would you be able to send the entire file either as a file or through a paste site? If I can't work out the issue I'll do some testing with the file on my end :)

**Comment by izeerF** [comment]
https://pastebin.com/Q9LhaVt0

**Comment by OakLoaf** [comment]
> https://pastebin.com/Q9LhaVt0

Your indentation appears to be quite off which is probably what is causing the issue
<img width="449" alt="Screenshot 2024-10-15 at 17 39 34" src="https://github.com/user-attachments/assets/3a76e848-48ef-482c-8b3e-fc50d0f0cade">

**Comment by izeerF** [comment]
its not actually like this, pastebin formated it like that i think

**Comment by OakLoaf** [comment]
Could you send the file itself in that case please

**Comment by izeerF** [comment]
okey i fixed it, for whatever reason i had to delete all the tabs and spaces and just redo them even tho it looked all good in 2 editors. But I got it. Thank You for all the help.

**Comment by OakLoaf** [comment]
No worries! Yaml does not support tab characters so that was likely the issue
